name: Checkly Tests

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

concurrency:
  group: checkly-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run-checkly-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Run Checkly tests (recorded)
        env:
          CHECKLY_API_KEY: ${{ secrets.CHECKLY_API_KEY }}
          CHECKLY_ACCOUNT_ID: ${{ secrets.CHECKLY_ACCOUNT_ID }}
        run: pnpm exec checkly test --record --reporter=list
