name: Vercel Deploy + Checkly Tests

on:
  push:
    branches-ignore: ["dependabot/**"]
  workflow_dispatch: {}

concurrency:
  group: vercel-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Vercel Deploy (Preview)
        id: vercel
        if: github.ref != 'refs/heads/main'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: .
          vercel-args: "--prebuilt"

      - name: Vercel Deploy (Production)
        id: vercel_prod
        if: github.ref == 'refs/heads/main'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: .
          vercel-args: "--prebuilt --prod"

      - name: Resolve Deployed URL
        id: resolve_url
        run: |
          PREVIEW_URL="${{ steps.vercel.outputs.preview-url }}"
          PROD_URL="${{ steps.vercel_prod.outputs.preview-url }}"
          URL="$PREVIEW_URL"
          if [ -z "$URL" ]; then URL="$PROD_URL"; fi
          if [ -z "$URL" ]; then URL="${{ secrets.PRODUCTION_URL }}"; fi
          echo "url=$URL" >> $GITHUB_OUTPUT

      - name: Run Checkly tests (recorded) against deployed URL
        env:
          CHECKLY_API_KEY: ${{ secrets.CHECKLY_API_KEY }}
          CHECKLY_ACCOUNT_ID: ${{ secrets.CHECKLY_ACCOUNT_ID }}
          PRODUCTION_URL: ${{ steps.resolve_url.outputs.url }}
        run: pnpm exec checkly test --record --reporter=list
